version: "1"
dev:
  config_1: config_val_1
  config_2: config_val_2
  config_3: config_val_3
uat:
  config_1: config_val_1
  config_2: config_val_2
  config_3: config_val_3
prod:
  config_1: config_val_1
  config_2: config_val_2
  config_3: config_val_3
